In [1]:
# importando pandas e usando pd como alias
import pandas as pd

In [17]:
# dados é um Dataframe
dados = pd.read_csv("datasus_ano_mes_atendimento.csv", encoding="ISO-8859-1", sep=";", skiprows=3, skipfooter=12, thousands=".", decimal=",")

<ipython-input-17-41e42e99fbd7>:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  dados = pd.read_csv("datasus_ano_mes_atendimento.csv", encoding="ISO-8859-1", sep=";", skiprows=3, skipfooter=12, thousands=".", decimal=",")

In [18]:
# utilizando o método '.head()' para exibir as 5 primeiras linhas do Dataframe dados
dados.head()

,Unidade da Federação,1992/Mar,1992/Abr,1993/Mai,1993/Dez,1994/Jan,1994/Fev,1994/Mai,1994/Ago,1994/Nov,...,2023/Dez,2024/Jan,2024/Fev,2024/Mar,2024/Abr,2024/Mai,2024/Jun,2024/Jul,2024/Ago,Total
0,11 Rondônia,-,-,-,-,-,-,-,-,-,...,11944255.06,11713667.81,11439176.48,13016771.41,13349073.12,12861282.55,9768106.57,6856004.53,3760689.79,1.488884e+09
1,12 Acre,-,-,-,-,-,-,-,-,-,...,4279531.59,4404809.58,4492196.94,5114225.71,5099228.73,4754614.50,4688673.93,3704966.38,2011641.58,6.265956e+08
2,13 Amazonas,-,-,-,-,-,-,-,-,-,...,18624814.74,21782845.52,19112100.43,22152090.77,21435715.70,22876391.30,20260259.52,17275473.78,6331333.43,2.772327e+09
3,14 Roraima,-,-,-,-,-,-,-,-,-,...,3279093.69,3046959.86,3096827.52,3121174.37,2884172.14,2188528.40,884722.40,96973.38,36840.18,4.755070e+08
4,15 Pará,-,-,-,-,-,-,-,-,-,...,50786654.84,52704888.70,51281721.02,54308506.00,55784755.34,55001120.94,43314313.68,34530139.71,14549941.58,6.699094e+09

In [19]:
# utilizando o método '.head()' para exibir as 5 últimas linhas do Dataframe dados
dados.tail()

,Unidade da Federação,1992/Mar,1992/Abr,1993/Mai,1993/Dez,1994/Jan,1994/Fev,1994/Mai,1994/Ago,1994/Nov,...,2023/Dez,2024/Jan,2024/Fev,2024/Mar,2024/Abr,2024/Mai,2024/Jun,2024/Jul,2024/Ago,Total
22,43 Rio Grande do Sul,-,-,-,-,-,-,-,-,-,...,1.117256e+08,1.207638e+08,1.111287e+08,1.252062e+08,1.279424e+08,1.113198e+08,1.114788e+08,93744439.03,37622294.14,1.760759e+10
23,50 Mato Grosso do Sul,-,-,-,-,-,-,-,-,-,...,2.564809e+07,2.699545e+07,2.599079e+07,2.834330e+07,2.781183e+07,2.535439e+07,1.801777e+07,10387844.00,3849001.55,3.410879e+09
24,51 Mato Grosso,-,-,-,-,-,-,-,-,-,...,2.225596e+07,2.289362e+07,2.366732e+07,2.528967e+07,2.767146e+07,2.490686e+07,2.127990e+07,17555319.80,6999654.47,3.166163e+09
25,52 Goiás,-,-,-,-,-,-,-,-,-,...,4.780130e+07,5.057052e+07,4.796994e+07,5.605247e+07,5.487748e+07,5.255375e+07,4.754742e+07,43800077.45,22197439.34,7.068621e+09
26,53 Distrito Federal,-,-,-,-,-,-,-,-,-,...,2.849657e+07,3.265231e+07,3.055140e+07,3.320516e+07,3.242985e+07,3.319041e+07,3.167540e+07,28653401.01,17658084.35,3.776514e+09

In [20]:
# dados2 é outro Dataframe
dados2 = pd.read_csv("datasus_ano_mes_processamento.csv", encoding="ISO-8859-1", skiprows=3, sep=";", skipfooter=12, thousands=".", decimal=",")

<ipython-input-20-996c1ec01d7b>:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  dados2 = pd.read_csv("datasus_ano_mes_processamento.csv", encoding="ISO-8859-1", skiprows=3, sep=";", skipfooter=12, thousands=".", decimal=",")

In [21]:
# utilizando o método '.head()' para exibir as 5 primeiras linhas do Dataframe dados2
dados2.head()

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2023/Dez,2024/Jan,2024/Fev,2024/Mar,2024/Abr,2024/Mai,2024/Jun,2024/Jul,2024/Ago,Total
0,11 Rondônia,1388528.39,2931283.42,1541682.52,1525314.96,1645953.84,1406150.68,3065279.01,3231494.61,3117178.63,...,10285428.64,12839765.04,11404441.80,12650347.02,11621160.07,13227789.61,14530979.75,14397621.45,13582796.81,1.488884e+09
1,12 Acre,902416.00,1497206.26,1794028.48,1730469.42,1819443.92,1828496.00,2511754.59,2089107.14,2275708.53,...,3503827.09,4308072.76,4092197.71,4819515.84,5560094.15,4374108.09,4484207.99,6335660.47,4843306.50,6.265956e+08
2,13 Amazonas,4735529.42,7118990.57,8196635.49,8259378.42,7831399.90,8477273.62,9368858.72,9352532.70,9363099.35,...,14875474.44,16497140.19,21053067.92,23549663.31,23454822.33,23233390.29,22504995.88,21887056.69,20165177.57,2.772327e+09
3,14 Roraima,657889.53,777939.31,718688.03,839994.39,862347.96,832440.66,996693.09,894271.18,910424.17,...,2944423.63,2983752.53,3160891.68,3466938.14,2733348.91,3156689.17,3372578.21,2492913.17,3340196.01,4.755070e+08
4,15 Pará,18864744.11,19553758.20,21937342.70,20842829.69,23249952.88,23240687.56,24002223.56,23341218.03,25172261.32,...,56139813.00,48849139.60,50671661.28,54205259.14,54632077.92,54159077.44,52962999.91,52418233.49,49525502.38,6.699094e+09

In [22]:
# utilizando o método '.head()' para exibir as 5 últimas linhas do Dataframe dados2
dados2.tail()

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2023/Dez,2024/Jan,2024/Fev,2024/Mar,2024/Abr,2024/Mai,2024/Jun,2024/Jul,2024/Ago,Total
22,43 Rio Grande do Sul,30931325.46,57363420.01,51547794.07,56673338.49,48397733.07,52413429.62,56636376.98,56113054.70,55356224.30,...,1.146325e+08,1.222493e+08,1.124649e+08,1.203585e+08,1.232611e+08,1.160477e+08,1.248992e+08,1.273685e+08,1.312901e+08,1.760759e+10
23,50 Mato Grosso do Sul,5377392.11,7002472.61,8423933.19,8797487.68,9770421.80,10905392.18,10249299.82,9671553.45,10218511.05,...,2.700727e+07,2.837560e+07,2.449435e+07,2.542334e+07,2.715953e+07,2.531263e+07,2.649010e+07,2.826470e+07,2.940529e+07,3.410879e+09
24,51 Mato Grosso,4795299.01,8684882.23,7886243.14,8794109.79,9231645.40,10221763.77,9163314.28,9243148.81,9052354.89,...,2.097024e+07,2.364745e+07,2.288853e+07,2.475580e+07,2.617643e+07,2.639414e+07,2.543263e+07,2.687115e+07,2.160401e+07,3.166163e+09
25,52 Goiás,15310637.29,22258668.68,21442515.75,20921212.45,21615970.67,18270043.87,20540517.13,20650730.67,20868443.56,...,5.151940e+07,5.164650e+07,4.738856e+07,5.519301e+07,5.584637e+07,5.543399e+07,5.239946e+07,5.894785e+07,5.412421e+07,7.068623e+09
26,53 Distrito Federal,4745919.19,7632480.67,9647203.26,11098732.99,12891719.72,12850125.67,12565646.74,13710857.89,13165106.20,...,2.946529e+07,3.187800e+07,2.949671e+07,3.250038e+07,3.400904e+07,3.427163e+07,3.213844e+07,3.467472e+07,3.639587e+07,3.776514e+09

In [24]:
# Média dos dados numéricos do Dataframe dados
dados.mean(numeric_only=True)

2007/Ago    3.049528e+05
2007/Set    7.881453e+05
2007/Out    2.440163e+06
2007/Nov    5.517354e+06
2007/Dez    1.233716e+07
                ...
2024/Mai    7.241331e+07
2024/Jun    6.438812e+07
2024/Jul    5.695299e+07
2024/Ago    3.054594e+07
Total       9.088244e+09
Length: 206, dtype: float64

In [25]:
# Visão geral de como o Dataframe dados funciona
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Columns: 328 entries, Unidade da Federação to Total
dtypes: float64(206), object(122)
memory usage: 69.3+ KB

In [27]:
# Média dos dados numéricos do Dataframe dados 2
dados2.mean(numeric_only=True)

2008/Jan    1.512685e+07
2008/Fev    2.271016e+07
2008/Mar    2.459419e+07
2008/Abr    2.543196e+07
2008/Mai    2.651125e+07
                ...
2024/Mai    7.319611e+07
2024/Jun    7.251213e+07
2024/Jul    7.558435e+07
2024/Ago    7.533484e+07
Total       9.088252e+09
Length: 200, dtype: float64

In [28]:
# Visão geral de como o Dataframe dados2 funciona
dados2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Columns: 202 entries, Unidade da Federação to Total
dtypes: float64(200), object(2)
memory usage: 42.7+ KB

In [30]:
# Ajuste na formatação padrão de python
pd.options.display.float_format = "{:.2f}".format

In [33]:
dados.mean(numeric_only=True)

2007/Ago       304952.77
2007/Set       788145.26
2007/Out      2440162.96
2007/Nov      5517354.05
2007/Dez     12337159.42
                ...
2024/Mai     72413313.83
2024/Jun     64388119.10
2024/Jul     56952988.52
2024/Ago     30545937.91
Total      9088244246.01
Length: 206, dtype: float64

In [34]:
dados2.mean(numeric_only=True)

2008/Jan     15126846.64
2008/Fev     22710158.12
2008/Mar     24594187.35
2008/Abr     25431957.83
2008/Mai     26511245.91
                ...
2024/Mai     73196107.94
2024/Jun     72512132.11
2024/Jul     75584351.56
2024/Ago     75334843.50
Total      9088251592.29
Length: 200, dtype: float64

In [39]:
# Selecionando apenas a primeira e última colunas (dados) - desafio Aula 1
dados.iloc[:,[0,-1]].head()

  Unidade da Federação         Total
0          11 Rondônia 1488884393.98
1              12 Acre  626595571.45
2          13 Amazonas 2772327408.24
3           14 Roraima  475506983.71
4              15 Pará 6699094107.75

In [40]:
# Selecionando apenas a primeira e última colunas (dados2) - desafio Aula 1
dados2.iloc[:,[0,-1]].head()

  Unidade da Federação         Total
0          11 Rondônia 1488884393.98
1              12 Acre  626595571.45
2          13 Amazonas 2772327408.24
3           14 Roraima  475506983.71
4              15 Pará 6699094107.75